stages:
  - build
  - deploy
  - codestyle

build-front:
  stage: build
  tags:
    - gpnmarket-front-ci
  script:
    - pwd | xargs /bin/bash /var/agent/front/01.sync.sh
    - /bin/bash /var/agent/front/02.npm_install.sh
    - /bin/bash /var/agent/front/03.ng_build_prod.sh
    - exit 0
  only:
    - master

deploy-staging:
  stage: deploy
  tags:
    - gpnmarket-front-ci
  script:
    - /bin/bash /var/agent/front/04.change_girs.sh
    - exit 0
  only:
    - master

codestyle-staging:
  stage: codestyle
  tags:
    - gpnmarket-front-ci
  script:
    - cd www
    - npm i tslint --no-optional
    - npm run tslint
    - exit 0
  only:
    - merge_requests
