stages:
  - deploy
  - build
  - codestyle

variables:
  DEPLOY_DIR: ./www

deploy-front:
  stage: deploy
  tags:
    - gpnmarket-front-ci
  script:
    - rsync -rlpoDcv --exclude="/www/src/app/config/*.ts" --delete-after $DEPLOY_DIR /var/www/html/gpnmarket_front
    - exit 0
  only:
    - master

build-staging:
  stage: build
  tags:
    - gpnmarket-front-ci
  script:
    - /bin/bash /var/agent/front/npm_install.sh
    - /bin/bash /var/agent/front/ng_build.sh
    - exit 0
  only:
    - master

codestyle-staging:
  stage: codestyle
  tags:
    - gpnmarket-front-ci
  script:
    - cd www
    - npm i tslint --no-optional
    - npm run tslint
    - exit 0
  only:
    - merge_requests