import { KimPriceOrder } from "../../common/models/kim-price-order";
import { KimPriceOrderType } from "../../common/enum/kim-price-order-type";
import { Guid } from "guid-typescript";
import { KimPriceOrderStatus } from "../../common/enum/kim-price-order-status";

export const KimPriceOrdersMock: KimPriceOrder[] = [
  {
    id: Guid.create().toString(),
    nsiId: 2730,
    name: "Произвольный ценовой запрос 1",
    regions: "123",
    deliveryAddress: "",
    deliveryConditions: "30 дней с даты доставки",
    dateResponse: "2021-03-30",
    dateDelivery: "2021-03-31",
    dateCreate: "03.04.2020",
    type: KimPriceOrderType.STANDART,
    status: KimPriceOrderStatus.DRAFT,
    forSmallBusiness: false,
    forProducer: false,
    forAuthorizedDealer: false,
    denyMaxPricePosition: false,
    russianProduction: false,
    positions: [
      {
        id: Guid.create().toString(),
        name: "Головка соединительная муфтовая ГМ-50",
        okpd2: "123141",
        quantity: 1,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ ТМК UP PF 88.9х7.34-R2-P110-PSL-1 ГОСТ 31446-2017",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ 73х5,5-Л ГОСТ 633-80 А, с внутренним защитным покрытием Majorpack",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
    ],
  },  {
    id: Guid.create().toString(),
    nsiId: 2730,
    name: "Произвольный ценовой запрос 1",
    regions: "123",
    deliveryAddress: "",
    deliveryConditions: "30 дней с даты доставки",
    dateResponse: "2021-03-30",
    dateDelivery: "2021-03-31",
    dateCreate: "03.04.2020",
    type: KimPriceOrderType.STANDART,
    status: KimPriceOrderStatus.DRAFT,
    forSmallBusiness: false,
    forProducer: false,
    forAuthorizedDealer: false,
    denyMaxPricePosition: false,
    russianProduction: false,
    positions: [
      {
        id: Guid.create().toString(),
        name: "Головка соединительная муфтовая ГМ-50",
        okpd2: "123141",
        quantity: 1,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ ТМК UP PF 88.9х7.34-R2-P110-PSL-1 ГОСТ 31446-2017",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ 73х5,5-Л ГОСТ 633-80 А, с внутренним защитным покрытием Majorpack",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
    ],
  },  {
    id: Guid.create().toString(),
    nsiId: 2730,
    name: "Произвольный ценовой запрос 1",
    regions: "123",
    deliveryAddress: "",
    deliveryConditions: "30 дней с даты доставки",
    dateResponse: "2021-03-30",
    dateDelivery: "2021-03-31",
    dateCreate: "03.04.2020",
    type: KimPriceOrderType.STANDART,
    status: KimPriceOrderStatus.DRAFT,
    forSmallBusiness: false,
    forProducer: false,
    forAuthorizedDealer: false,
    denyMaxPricePosition: false,
    russianProduction: false,
    positions: [
      {
        id: Guid.create().toString(),
        name: "Головка соединительная муфтовая ГМ-50",
        okpd2: "123141",
        quantity: 1,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ ТМК UP PF 88.9х7.34-R2-P110-PSL-1 ГОСТ 31446-2017",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ 73х5,5-Л ГОСТ 633-80 А, с внутренним защитным покрытием Majorpack",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
    ],
  },  {
    id: Guid.create().toString(),
    nsiId: 2730,
    name: "Произвольный ценовой запрос 1",
    regions: "123",
    deliveryAddress: "",
    deliveryConditions: "30 дней с даты доставки",
    dateResponse: "2021-03-30",
    dateDelivery: "2021-03-31",
    dateCreate: "03.04.2020",
    type: KimPriceOrderType.STANDART,
    status: KimPriceOrderStatus.DRAFT,
    forSmallBusiness: false,
    forProducer: false,
    forAuthorizedDealer: false,
    denyMaxPricePosition: false,
    russianProduction: false,
    positions: [
      {
        id: Guid.create().toString(),
        name: "Головка соединительная муфтовая ГМ-50",
        okpd2: "123141",
        quantity: 1,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ ТМК UP PF 88.9х7.34-R2-P110-PSL-1 ГОСТ 31446-2017",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
      {
        id: Guid.create().toString(),
        name: "Труба НКТ 73х5,5-Л ГОСТ 633-80 А, с внутренним защитным покрытием Majorpack",
        okpd2: "123141",
        quantity: 12,
        okei: "123123",
      },
    ],
  },
];
