export enum LotWorkflowSteps {
  OFFERS_GATHERING = 'OFFERS_GATHERING',
  ARCHIVE = 'ARCHIVE',
  PUBLISHED = 'PUBLISHED',
  PRICE_REDUCTION = 'PRICE_REDUCTION',
  WINNER_CHOICE = 'WINNER_CHOICE',
  WINNER_PRICE_REDUCTION = 'WINNER_PRICE_REDUCTION',
  WAITING_FOR_RESULTS_PROTOCOL = 'WAITING_FOR_RESULTS_PROTOCOL',
  DRAFT = 'DRAFT',
  ON_SUPPLIER_APPROVAL = 'ON_SUPPLIER_APPROVAL',
  ON_CUSTOMER_APPROVAL = 'ON_CUSTOMER_APPROVAL',
  IN_PROGRESS = 'IN_PROGRESS'
}
