export enum PurchaseWorkflowStepStatuses {
  // потребность
  OFFERS_GATHERING = 'OFFERS_GATHERING',
  ARCHIVE = 'ARCHIVE',

  // процедура
  PUBLISHED = 'PUBLISHED',
  PRICE_REDUCTION = 'PRICE_REDUCTION',
  WINNER_CHOICE = 'WINNER_CHOICE',
  WINNER_PRICE_REDUCTION = 'WINNER_PRICE_REDUCTION',
  WAITING_FOR_RESULTS_PROTOCOL = 'WAITING_FOR_RESULTS_PROTOCOL',

  // заказ
  DRAFT = 'DRAFT',
  ON_CUSTOMER_APPROVAL = 'ON_CUSTOMER_APPROVAL',
  ON_SUPPLIER_APPROVAL = 'ON_SUPPLIER_APPROVAL'
}
