export enum AgreementAction {
  COMPLETE_REQUEST = 'COMPLETE_REQUEST',
  REQUEST_AGREEMENT = 'REQUEST_AGREEMENT',
  REVIEW_TP = 'REVIEW_TP',
  RESULTS_AGREEMENT_CP = 'RESULTS_AGREEMENT_CP',
  RESULTS_AGREEMENT_TCP = 'RESULTS_AGREEMENT_TCP'
}
