export enum ContractStatus {
  NEW = 'NEW',
  ON_APPROVAL = 'ON_APPROVAL',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  CONFIRMED_BY_CUSTOMER_WO_SIGN = 'CONFIRMED_BY_CUSTOMER_WO_SIGN',
  SIGNED = 'SIGNED',
  SIGNED_BY_CUSTOMER = 'SIGNED_BY_CUSTOMER',
  SIGNED_BY_SUPPLIER = 'SIGNED_BY_SUPPLIER',
  ARCHIVE = 'ARCHIVE'
}
