export enum PositionCancelReason {
  NO_PROPOSALS = 'NO_PROPOSALS',
  COMMERCIAL_PROPOSALS_REJECTED = 'COMMERCIAL_PROPOSALS_REJECTED',
  TECHNICAL_PROPOSALS_REJECTED = 'TECHNICAL_PROPOSALS_REJECTED',
  CUSTOMER_IGNORE = 'CUSTOMER_IGNORE',
  OTHER = 'OTHER'
}
