export enum RequestPositionWorkflowSteps {
  NEW = 'NEW',
  PROPOSALS_PREPARATION = 'PROPOSALS_PREPARATION',
  RESULTS_AGREEMENT = 'RESULTS_AGREEMENT',
  WINNER_SELECTED = 'WINNER_SELECTED',
  CONTRACT_SIGNING = 'CONTRACT_SIGNING',


}
