export enum RequestPositionWorkflowSteps {
  NEW = 'NEW',
  PROPOSALS_PREPARATION = 'PROPOSALS_PREPARATION',
  RESULTS_AGREEMENT = 'RESULTS_AGREEMENT',
  CONTRACT_SIGNING_BY_SUPPLIER = 'CONTRACT_SIGNING_BY_SUPPLIER',
  CONTRACT_SIGNING_BY_CUSTOMER = 'CONTRACT_SIGNING_BY_CUSTOMER',

}
