export enum TechnicalProposalsStatus {
  NEW = 'NEW',
  SENT_TO_REVIEW = 'SENT_TO_REVIEW',
  ACCEPTED = 'ACCEPTED',
  PARTIALLY_ACCEPTED = 'PARTIALLY_ACCEPTED',
  CANCELED = 'CANCELED',
  DECLINED = 'DECLINED'
}
