export enum AgreementAction {
  PROCESS_REQUEST = 'PROCESS_REQUEST',
  WORK_ON_REQUEST = 'WORK_ON_REQUEST',
  PROVIDE_TP = 'PROVIDE_TP',
  PROVIDE_CP = 'PROVIDE_CP',
  PROVIDE_TCP = 'PROVIDE_TCP',
  CORRECT_TP = 'CORRECT_TP',
  PROCESS_WINNER_SELECTED_CP = 'PROCESS_WINNER_SELECTED_CP',
  PROCESS_WINNER_SELECTED_TCP = 'PROCESS_WINNER_SELECTED_TCP',
  SEND_CONTRACT_AGREEMENT = 'SEND_CONTRACT_AGREEMENT',
  CORRECT_CONTRACT = 'CORRECT_CONTRACT',
  SIGN_CONTRACT = 'SIGN_CONTRACT'
}
