export enum OrderStatus {
  PUBLISHED = 'PUBLISHED',
  WAIT_FOR_SUPPLIER_CONFIRM = 'WAIT_FOR_SUPPLIER_CONFIRM',
  WAIT_FOR_CUSTOMER_CONFIRM = 'WAIT_FOR_CUSTOMER_CONFIRM',
  WAIT_FOR_PAYMENT = 'WAIT_FOR_PAYMENT',
  CANCELED = 'CANCELED',
}
