export enum ParamName {
  ORDER_ADDITIONAL_INFO = 'ORDER_ADDITIONAL_INFO',

  SUPPLIER_RESPONSE_DATE = 'SUPPLIER_RESPONSE_DATE',

  DELIVERY_ADDRESS = 'DELIVERY_ADDRESS',
  DELIVERY_DATE = 'DELIVERY_DATE',
  DELIVERY_COST = 'DELIVERY_COST',
}
