export enum DocumentExtension {
  csv = "csv",
  doc = "doc",
  docx = "doc",
  gif = "gif",
  jpg = "jpg",
  pdf = "pdf",
  png = "png",
  ppt = "ppt",
  rar = "rar",
  rtf = "rtf",
  tiff = "tiff",
  txt = "txt",
  undefined = "undefined",
  xls = "xls",
  xlsx = "xls",
  zip = "zip",
}
